### ISSUE TITLE
[WebToolsE2E] When deploying eShopLite, if I choose to expose catalogdbmanager publicly, I still get a 404 from the deployed app

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire-samples#110]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [latest build, includes Aspire 8.0.0-preview.3.24105.21 ]
3. Apply NuGet Feeds
4. Install Docker Desktop for Windows

**REPRO STEPS**
1. Clone aspire-samples repo from preview.3 branch
2. Update NuGet.config to use the correct feeds
3. Open samples\eShopLite.sln
4. Build and run solution locally
5. In the Dashboard, if you click the Endpoint for 'catalogdbmanager', you can see the status is 'Healthy'
    ![image](https://github.com/dotnet/aspire-samples/assets/8246794/cacb9560-2ab9-47ad-9f67-045ea621f116)
6. Open the solution folder in a Command Prompt
7. Run `azd init` to initialize the app for deployment
    - When running `azd init` choose to expose both catalogdbmanager and frontend to the Internet
    - ![image](https://github.com/dotnet/aspire-samples/assets/8246794/d8320473-ee7e-4347-b2be-68a161afabee)
8. Run `azd up` to deploy to Azure

**ACTUAL**
Deployment completes fine and you can see that catalogdbmanager and frontend are available publicly (i.e. there's no 'internal' in the URL)

![image](https://github.com/dotnet/aspire-samples/assets/8246794/4b64f37d-2123-49d2-b6c2-e9acc9404c75)

catalogdbmanager fails to load
![image](https://github.com/dotnet/aspire-samples/assets/8246794/50586731-2273-4221-92f3-e4cc807d2d34)

frontend loads fine though
![image](https://github.com/dotnet/aspire-samples/assets/8246794/eb7cf8e1-73a5-4899-9ec7-6c52d0a6fccc)

**EXPECTED**
I can get status as 'Healthy' when I hit the Endpoint of the deployed catalogdbmanager.

**Comment by danmoseley** [comment]
closing as resolved

**Comment by v-sherryfan** [comment]
@balachir Still reproducing on latest `preview.5` branch using VS 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12], I opened a new issue https://github.com/dotnet/aspire-samples/issues/188 to track.

/cc: @DamianEdwards @danmoseley
