### ISSUE TITLE
[WebToolsE2E] When deploying Aspire-Samples/ClientAppsIntegration solution, running 'azd up' failed with: 400 Bad Request InvalidParameterValueInContainerTemplate

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire-samples#112]
**REGRESSION INFO**: Also repro on Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [latest build, includes Aspire 8.0.0-preview.3.24105.21 ]
3. Apply NuGet Feeds
4. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone aspire-samples repo from preview.3 branch
2. Update NuGet.config to use the correct feeds
3. Open samples\ClientAppsIntegration.sln
4. Build
5. Right-click solution > Open Folder in File Explorer. In the opened folder, click any place > Open in Terminal
6. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter.
7. When running azd init choose to expose 'apiservice' to the Internet
8. Run azd up to deploy to Azure

**ACTUAL**:

Deployment service winformsclient failed:
ERROR: failed deploying service 'winformsclient': failing invoking action 'deploy', updating container app service: applying manifest: PUT https://management.azure.com/subscriptions/07268dd7-4c50-434b-b1ff-67b8164edb41/resourceGroups/rg-08aspcient/providers/Microsoft.App/containerApps/winformsclient

RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidParameterValueInContainerTemplate

{
  "error": {
    "code": "InvalidParameterValueInContainerTemplate",
    "message": "The following field(s) are either invalid or missing. Field 'template.containers.winformsclient.image' is invalid with details: 'Invalid value: \"acrubajetxnxj2xa.azurecr.io/azd-deploy-winformsclient-1707380624\": GET https:: MANIFEST_UNKNOWN: manifest tagged by \"latest\" is not found; map[Tag:latest]';."
  }
}

TraceID: 3edf11edd0f29a99b0f3e5774c272724

![image](https://github.com/dotnet/aspire-samples/assets/82028229/a1c2690b-8bf5-4eb7-be76-48f3f1672b92)

**EXPECTED**
Deployment can succeed.

**Comment by DamianEdwards** [comment]
This sample hasn't been authored to support deployment. Obviously, a WinForms app can't be deployed to Azure Container Apps via azd. Easiest fix would be to update the sample to explicitly exclude the client projects from the publish manifest.

**Comment by v-sherryfan** [comment]
Not repro on latest `preview.5` branch using VS 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12]
