### ISSUE TITLE
Add zip releases for samples

### ISSUE THREAD

**Issue by jfreitas** [dotnet/aspire-samples#116]
Sorry if I'm missing something obvious but some of the sample blog posts say to "download and unzip the sample" but there's no link to a zip in the post or in the sample readmes I've looked at.

For example:
https://learn.microsoft.com/en-us/samples/dotnet/aspire-samples/aspire-metrics/
https://github.com/dotnet/aspire-samples/tree/main/samples/Metrics
https://learn.microsoft.com/en-us/samples/dotnet/aspire-samples/aspire-dapr/

I know I can just clone the repo but it was a little confusing

**Comment by timheuer** [comment]
@IEvangelist is this something configurable in the samples browser?

**Comment by IEvangelist** [comment]
> @IEvangelist is this something configurable in the samples browser?

Hi @timheuer, the zip functionality was removed more than a year ago now. It's not something that we can add back, as it's a platform limitation (removed feature). We should be telling people in blog posts that they can clone the samples repo instead and open the specific sample solution/project.

**Comment by timheuer** [comment]
Right @IEvangelist but it appears there may be some boilerplate language in the samples browser itself? all seem to include that step:
![image](https://github.com/dotnet/aspire-samples/assets/4821/e4933f89-3611-490b-99b0-1ff48ac6c2f9)
