### ISSUE TITLE
Angular Docker image doesn't respond when run as container

### ISSUE THREAD

**Issue by timheuer** [dotnet/aspire-samples#122]
Unclear if this is an azd or Angular sample issue, but when deploying the AspireWithJavaScript sample to Azure using azd, all the front-ends work except the Angular one, it fails to respond. No errors in log stream and appears to start, so I'm not sure where the issue lies yet, but logging the issue here to start.

**Comment by timheuer** [comment]
@IEvangelist did you ever get the Docker image for the angular app to work? I'm not even getting it working locally in Docker desktop...

**Comment by IEvangelist** [comment]
> @IEvangelist did you ever get the Docker image for the angular app to work? I'm not even getting it working locally in Docker desktop...

@timheuer, I thought so, let me double check and report back.

**Comment by danmoseley** [comment]
@IEvangelist can we close then
