### ISSUE TITLE
[WebToolsE2E][Aspire] F5 to run aspire-samples/OrleansVoting solution, clicking on any endpoint of "voting-fe" on the dashboard will throw an exception: Exception of type 'Microsoft.AspNetCore.Components.NavigationException'.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#129]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [ includes Aspire 8.0.0-preview.3.24105.21 ]
3. Install Docker Desktop for Windows
4. Install azd [1.6.1]

**REPRO STEPS**

1. Clone aspire-samples repo from main branch
2. Open samples\OrleansVoting.sln
3. Build and F5
4. Clicking on any endpoint of 'voting-fe'

**ACTUAL:**
Microsoft.AspNetCore.Components.NavigationException: 'Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown.'
![image](https://github.com/dotnet/aspire-samples/assets/71361488/74aa7464-da49-4b5d-8d98-59794e00f7a1)
![image](https://github.com/dotnet/aspire-samples/assets/71361488/fb1e4850-0f6d-42fb-8203-5d88b34f1ea8)

**Note**

1. But do Ctrl+F5, it works fine and without any errors in Console logs.

**EXPECTED**
Clicking on any endpoint of 'voting-fe' works without any exception.

**Comment by DamianEdwards** [comment]
Can't repro this with preview.4 bits, closing.

**Comment by v-sherryfan** [comment]
Verified this issue that still reproduced on preview.4 branch, I have opened another issue [#145](https://github.com/dotnet/aspire-samples/issues/145) to track it.
