### ISSUE TITLE
[WebToolsE2E][Aspire] Building the eShopLite/AspireWithNode solution using 8.0 P4 gives some errors: "Package Microsoft.Extensions.ServiceDiscovery 9.0.0-preview.1.24113.3 is not compatible with net8.0."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#130]
**REGRESSION INFO:** Worked fine on Aspire 8.0.0 preview 3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 2 [ includes Aspire 8.0.0-preview.3.24105.21 ]
3. Install Docker Desktop for Windows
4. Install Aspire.ProjectTemplates.8.0.0-preview.4.24125.2
5. Apply nuget dotnet8 feed

**REPRO STEPS**

1. Clone aspire-samples repo from main branch
2. Update Aspire version 8.0 P3 to latest 8.0 P4
    - Open global.json and update sdk version 
      ![image](https://github.com/dotnet/aspire-samples/assets/71361488/6eb317be-8224-473b-8601-4d51e59c0c9d)
    - Open NuGet.config and add dotnet8feed
      ![image](https://github.com/dotnet/aspire-samples/assets/71361488/ed95d40d-da41-4b0c-b1c9-7145e34b8cb0)
   - Open Directory.Packages.props and update Aspire version to latest 8.0 P4
     ![image](https://github.com/dotnet/aspire-samples/assets/71361488/bcbf57c0-7837-4502-952c-3cd3015073e7)

6. Open samples\eShopLite.sln
7. Build solution

**ACTUAL:**
Warning	NU1603	eShopLite.ServiceDefaults depends on Microsoft.Extensions.ServiceDiscovery (>= 8.0.0-preview.4.24125.2) but Microsoft.Extensions.ServiceDiscovery 8.0.0-preview.4.24125.2 was not found. An approximate best match of Microsoft.Extensions.ServiceDiscovery 9.0.0-preview.1.24113.3 was resolved.	
Error NU1202 Package Microsoft.Extensions.ServiceDiscovery 9.0.0-preview.1.24113.3 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package Microsoft.Extensions.ServiceDiscovery 9.0.0-preview.1.24113.3 supports: net9.0 (.NETCoreApp,Version=v9.0)
![image](https://github.com/dotnet/aspire-samples/assets/71361488/6dfb4d0a-a999-4bc5-a405-a7bac7635abc)

**EXPECTED**
Open eShopLite solution without any errors.

**Additional Info**
![image](https://github.com/dotnet/aspire-samples/assets/71361488/013ba4ca-722e-4d5f-8734-077fed010dbc)

**Comment by DamianEdwards** [comment]
I think you're using the wrong feed. Preview 4 packages now come from the dotnet-tools feed as we've branched for release.

This sample is working fine in the [preview.4 update PR](https://github.com/dotnet/aspire-samples/pull/134) so I'm closing this as no repro.
