### ISSUE TITLE
[WebToolsE2E][Aspire] F5 / Ctrl+F5 to run the samples\Metrics solution fails with error: "could not create the container, xxx includes invalid characters for a local volume name".

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#139]
**REGRESSION INFO:** Worked fine on Aspire 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 2 [ includes Aspire 8.0.0-preview.4.24128.4 ]
3. Apply NuGet dotnet-tools Feeds
4. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone aspire-samples repo from main branch
2. Checkout the `Preview.4` branch
3. Update sdk version to `8.0.300-preview.24101.10` in global.json
4. Update Aspire version to latest `8.0.0-preview.4.24128.4` in Directory.Packages.props
5. Open samples\Metrics.sln
6. F5 / Ctrl+F5

**ACTUAL:**
fail: Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0]
      could not create the container    {"Container": {"name":"grafana"}, "Reconciliation": 2, "error": "CreateContainer command returned error code 1 Stdout: '' Stderr: 'Error response from daemon: create ../grafana/config: \"../grafana/config\" includes invalid characters for a local volume name, only \"[a-zA-Z0-9][a-zA-Z0-9_.-]\" are allowed. If you intended to pass a host directory, use absolute path\n'"}
![image](https://github.com/dotnet/aspire-samples/assets/71361488/2ea4598c-a770-4dc9-a9e4-2195736b27e2)

**EXPECTED**
F5 / Ctrl+F5 is successful.

**Comment by DamianEdwards** [comment]
This is caused by the sample using the wrong method (`WithVolumeMount` instead of `WithBindMount`). Fixing in the preview.4 PR.

**Comment by v-sherryfan** [comment]
Verified this issue that is not reprodoce on VS 17.10 P2 ( Include 8.0.0-preview.4.24156.9 ).
