### ISSUE TITLE
[WebToolsE2E][Aspire] Running "azd init" to initialize Aspire-Samples/OrleansVoting solution fails with error: "configuring ingress for project voting-fe: the transport property of all bindings should match".

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#144]
**REGRESSION INFO:** Worked fine on Aspire 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 2 [ Includes Aspire 8.0.0-preview.4.24129.7 ]
3. Apply NuGet dotnet-tools Feeds
4. Install Docker Desktop for Windows
5. Install azd [1.7.0-beta.1-daily]

**REPRO STEPS**

1. Clone aspire-samples repo from main branch
2. Checkout the `preview.4` branch
3. Update Aspire version in Directory.Packages.props to latest 8.0.0-previeew.4.24129.7 
4. Open samples\OrleansVoting.sln
5. Build solution
6. Deploy using azd
    - Open the solution folder in a Command Prompt
    - Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter

**ACTUAL:**
ERROR: configuring ingress for project voting-fe: the transport property of all bindings should match
![image](https://github.com/dotnet/aspire-samples/assets/71361488/caaef8a3-6217-4ae0-9379-a6c4dd37ff93)

**EXPECTED**
Running 'azd init' successfully
![image](https://github.com/dotnet/aspire-samples/assets/71361488/0be6b7ef-d3cc-4875-aaa7-f1e12079f6e0)

**Comment by DamianEdwards** [comment]
@ReubenBond @davidfowl @bradygaster is it possible to make the Orleans sample deployable via AZD?

**Comment by ReubenBond** [comment]
This is a new error - it was possible to deploy Orleans to ACA in Preview 3

**Comment by DamianEdwards** [comment]
OK thanks. Who should I assign this to?

**Comment by ReubenBond** [comment]
I suppose it's me, but I don't know how we fix this. The issue seems to be that we have some internal (TCP) and external (HTTP(S)) endpoints. I'm not sure how we can express that in AZD:
```json
"bindings": {
  "orleans-silo": {
    "scheme": "tcp",
    "protocol": "tcp",
    "transport": "tcp"
  },
  "orleans-gateway": {
    "scheme": "tcp",
    "protocol": "tcp",
    "transport": "tcp"
  },
  "http": {
    "scheme": "http",
    "protocol": "tcp",
    "transport": "http"
  },
  "https": {
    "scheme": "https",
    "protocol": "tcp",
    "transport": "http"
  }
}
```

**Comment by DamianEdwards** [comment]
That's new for preview.4?

**Comment by ReubenBond** [comment]
Yes, in p3 we weren't modelling the internal endpoints in the app model. We added that in p4 so that we could have DCP allocate ports on launch to prevent port conflicts when running with > 1 replica. We could hide those internal endpoints when publishing the manifest, as a workaround, but we ultimately need a better solution.

**Comment by DamianEdwards** [comment]
ACA does [support additional TCP ingress ports](https://learn.microsoft.com/azure/container-apps/ingress-overview#additional-tcp-ports) for a service but AZD doesn't currently support configuring them based on the Aspire manifest.

@davidfowl I know you were looking at this recently. Is this tracked anywhere yet?

**Comment by DamianEdwards** [comment]
Ah seems it's tracked here: https://github.com/Azure/azure-dev/issues/3267

**Comment by v-sherryfan** [comment]
Not repro on latest `preview.5` branch using VS 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12]
