### ISSUE TITLE
[WebToolsE2E][Aspire] F5 to run aspire-samples/OrleansVoting solution, clicking on any endpoint of "voting-fe" on the dashboard will throw an exception: Exception of type 'Microsoft.AspNetCore.Components.NavigationException'.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#145]
**REGRESSION INFO:** Also repro on Aspire 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 2 [ Includes Aspire 8.0.0-preview.4.24129.7 ]
3. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone aspire-samples repo from main branch
2. Checkout the `preview.4` branch
3. Update Aspire version in Directory.Packages.props to latest 8.0.0-previeew.4.24129.7 
4. Open samples\OrleansVoting.sln
5. Build and F5
6. Clicking on any endpoint of 'voting-fe' in the dashboard

**ACTUAL:**
Microsoft.AspNetCore.Components.NavigationException: 'Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown.'
![image](https://github.com/dotnet/aspire-samples/assets/71361488/ad90be68-fda1-438b-8a42-046e6b566289)
![image](https://github.com/dotnet/aspire-samples/assets/71361488/418f12c2-b122-4b2e-b60c-c1a0834c3e59)

**Note**

1. But do Ctrl+F5, it works fine and without any errors in Console logs.

**EXPECTED**
Clicking on any endpoint of 'voting-fe' works without any exception.

**Comment by DamianEdwards** [comment]
I can't reproduce this on preview.4 bits.

@ReubenBond?

**Comment by v-sherryfan** [comment]
Unable to reproduce on 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12] using aspire-samples `main` branch.
