### ISSUE TITLE
Fail to deploy service "winformsclient" for sample "ClientAppsIntegration"

### ISSUE THREAD

**Issue by Menghua1** [dotnet/aspire-samples#147]
**Describe the issue:**
Run the `azd deploy` command failed and the error message is as follows:
![image](https://github.com/dotnet/aspire-samples/assets/111940661/46448ad0-87df-4a11-83fd-1bc9b30112aa)
**Repro Steps**:
1. Clone code.
2. Run command `cd ClientAppsIntegration`.
3. Run command `azd init` -> choose use code from folder and accept the Aspire project -> When asking which services to expose, select none service -> leave all other services unchecked.
4. Run command `azd up`.

**Environment:**
- Azd version: `azd version 1.7.0-beta.1-daily.3564805 (commit 81f3efd1049889762d01ca46a35630005b45f0b5)`
- Aspire version: `8.0.0-preview.4.24156.9`
- Sample: [ClientAppsIntegration](https://github.com/dotnet/aspire-samples/tree/preview.4/samples/ClientAppsIntegration)

**Expected behavior:**
"Winformsclient" service can be deployed successfully.

@rajeshkamal5050, @vhvb1989 for notification.

**Comment by moljac** [comment]
Isn't that Windows Desktop App (`winformsclient`)?  Why and how would you deploy it on Azure?

OK. I am not Azure expert, but if this exists I would like to learn.

**Comment by DamianEdwards** [comment]
Yeah the client apps can't be deployed by azd. I'm updating the sample to exclude them from the publish manifest.
