### ISSUE TITLE
Fail to run `azd init` command for sample “OrleansVoting”

### ISSUE THREAD

**Issue by Menghua1** [dotnet/aspire-samples#148]
**Describe the issue:**
Run the `azd init` command and select no services to expose, the following error occurs:
![image](https://github.com/dotnet/aspire-samples/assets/111940661/eda2c17c-065b-4580-a4ae-37dde448fbe4)
![image](https://github.com/dotnet/aspire-samples/assets/111940661/4432e30f-ba0a-43fd-99dc-458206e0a0dd)

**Repro Steps**:
1. Clone code.
2. Run command `cd OrleansVoting`.
3. Run command `azd init` -> choose use code from folder and accept the Aspire project -> When asking which services to expose, select none service -> leave all other services unchecked.

**Environment:**
- Azd version: `azd version 1.7.0-beta.1-daily.3564805 (commit 81f3efd1049889762d01ca46a35630005b45f0b5)`
- Aspire version: `8.0.0-preview.4.24156.9`
- Sample: [OrleansVoting](https://github.com/dotnet/aspire-samples/tree/preview.4/samples/OrleansVoting)

**Expected behavior:**
`azd init` command can be executed successfully.

@rajeshkamal5050, @vhvb1989 for notification.

**Comment by rajeshkamal5050** [comment]
@davidfowl @DamianEdwards @vhvb1989 https://github.com/dotnet/aspire-samples/tree/preview.4/samples/OrleansVoting is this expected to work with Azd?

**Comment by DamianEdwards** [comment]
@bradygaster ?

**Comment by bradygaster** [comment]
will look at this and try to resolve asap.

**Comment by bradygaster** [comment]
I tried the recently-updated-to-9.0 code just now. `azd init` worked, and `azd up` is running. I noticed @Menghua1 mentioned their `azd` version being `1.7.0-beta.1-daily.3564805`. I'm on version `azd version 1.11.0 (commit 5b92e0687e1fa96dfc8292f4b900c0c58610b6a5)`. Could you update your `azd` and try again with these updated projects and let us know if the problem remains?

**Comment by Menghua1** [comment]
@bradygaster According to the latest code and azd version test, this issue can no longer be reproduced, thank you.
