### ISSUE TITLE
DatabaseMigration example fails because database does not exist.

### ISSUE THREAD

**Issue by julionav** [dotnet/aspire-samples#159]
### Problem

When using a `MigrationService` as shown on the `DatabaseMigration`  example, I got an error saying that the database was not created. 

This seems to be caused by the transaction used alongside the call to `MigrateAsync`, and can be solved by removing it. However, we do want to run the migrations inside a transaction, but I am not sure how can we create the databa (if it doesn't exist), the run the migrations. 

```
private static async Task InitializeDatabaseAsync(AppDbContext dbContext, CancellationToken cancellationToken)
    {
        using var activity = s_activitySource.StartActivity("Migrating database", ActivityKind.Client);
        await dbContext.Database.MigrateAsync(cancellationToken);
        //var strategy = dbContext.Database.CreateExecutionStrategy();
        //await strategy.ExecuteAsync(async () =>
        //{
        //    await using var transaction = await dbContext.Database.BeginTransactionAsync(cancellationToken);
        //    await dbContext.Database.MigrateAsync(cancellationToken);
        //    await transaction.CommitAsync(cancellationToken);
        //});
    } 
```

### Versions
- aspire 8 preview 4
- Npgsql 8 preview 4

**Comment by julionav** [comment]
Hold on. This is already fixed? It looks like I was using the [aspire/playground](https://github.com/dotnet/aspire/blob/main/playground/DatabaseMigration/DatabaseMigration.MigrationService/ApiDbInitializer.cs) sample instead of the one in this repo. The playground example should probably be removed, I'm leaving this open so the confusion is noticed 🙏

**Comment by DamianEdwards** [comment]
Closing as this is resolved it seems.
