### ISSUE TITLE
[WebToolsE2E][Aspire] In the AspirewithDapr dashboard, clicking on 'webfrontend' endpoint and then navigating to 'Weather' page shows error: "The gRPC endpoint must use http or https."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#170]
**REGRESSION INFO:** Worked on Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 3 [ Includes Aspire 8.0.0-preview.5.24178.3 and SDK 8.0.300-preview.24170.4 ]
3. Install latest Aspire 8.0 P5 [8.0.0-preview.5.24179.3]
4. Apply NuGet dotnet-tools Feed
5. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone aspire-samples repo
2. Checkout the `preview.5` branch
3. Update sdk version to 8.0.300-preview.24170.4 in global.json
4. Open samples\AspirewithDapr.sln
5. Build and F5
6. In the dashboard, click on 'webfrontend' endpoint > go to "Weather" page

**ACTUAL**

Running with `http` is the same as below.
![image](https://github.com/dotnet/aspire-samples/assets/71361488/b0a0ecfe-9237-45e5-a6e0-057b7d1a8f25)
![image](https://github.com/dotnet/aspire-samples/assets/71361488/ebff0fd3-91c9-4b05-9dee-b6cf4528f936)

**EXPECTED**

![image](https://github.com/dotnet/aspire-samples/assets/71361488/eceb3d21-2d1f-4ee8-8da0-ae99ae9c1991)

**Comment by DamianEdwards** [comment]
Samples require updating to support preview.5. See #172

**Comment by v-sherryfan** [comment]
Not repro on latest `preview.5` branch using VS 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12]
