### ISSUE TITLE
Fail to run "azd init" for sample "Metrics" 

### ISSUE THREAD

**Issue by Menghua1** [dotnet/aspire-samples#180]
**Describe the issue:**
Run the `azd init` command failed and the error message is as follows:
![image](https://github.com/dotnet/aspire-samples/assets/111940661/fb76707a-0607-40ec-b339-e378fa8cab96)

**Repro Steps:**
1. Clone code.
2. Run command `cd samples/Metrics`.
3. Run command `azd init`.

**Environment:**
- Azd version: `azd version 1.8.0-beta.1-daily.3661089 (commit d078aeb7cf1497aa7c8d629d2f6d434554e0cd9a)`
- Aspire version: `8.0.0-preview.5.24201.12`
- Sample: [Metrics](https://github.com/dotnet/aspire-samples/tree/preview.5/samples/Metrics)
- Branch: `preview.5`

**Expected behavior:**
`azd init` command can be executed successfully.

@rajeshkamal5050, @vhvb1989 for notification.

**Comment by rajeshkamal5050** [comment]
@vhvb1989 is `executable.v0` supported in Azd?

**Comment by Menghua1** [comment]
@rajeshkamal5050, @vhvb1989 It is now impossible to reproduce this issue, I will close this issue.
