### ISSUE TITLE
[WebToolsE2E][Aspire] Running the AspireShop solution fails with error: "could not create the container..., container has failed to start...".

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#183]
**REGRESSION INFO:** Worked on Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 3 [ Includes Aspire 8.0.0-preview.5.24201.12 and SDK 8.0.300-preview.24203.14 ]
3. Apply NuGet dotnet-tools Feed
5. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone aspire-samples repo
2. Checkout the `preview.5` branch
3. Update sdk version to 8.0.300-preview.24203.14 in global.json
4. Open samples\AspireShop.sln
5. Build
6. F5 / Ctrl+F5

**ACTUAL**

- do F5 / Ctrl+F5 using https
![image](https://github.com/dotnet/aspire-samples/assets/71361488/9e189ff5-f04e-4b63-9803-52669934d365)
![image](https://github.com/dotnet/aspire-samples/assets/71361488/e160baa4-26c8-4f87-b72e-0d7cb5485b55)
![image](https://github.com/dotnet/aspire-samples/assets/71361488/892aa3c1-291f-440b-864a-db5220f6c667)

**EXPECTED**

The dashboard page displays normally without any exceptions when running the AspireShop solution.

**Comment by davidfowl** [comment]
Is your docker healthy? What happens if you manually pull the image?

**Comment by v-sherryfan** [comment]
@davidfowl Yeah, I thought my docker was unhealthy before, so I tried restarting my machine and couldn't get the error "Unable to find image..." but saw another error as shown below.
![image](https://github.com/dotnet/aspire-samples/assets/71361488/9febc842-50b6-491a-a970-41563ba63eed)

**Comment by balachir** [comment]
@v-sherryfan if you created an Aspire Starter app with Redis, did that run successfully?

@davidfowl I'm not seeing this issue that Sherry ran into but I'm seeing a different issue - https://github.com/dotnet/aspire-samples/issues/185

**Comment by v-sherryfan** [comment]
Unable to reproduce on 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12] using aspire-samples `main` branch.
