### ISSUE TITLE
[WebToolsE2E][Aspire] When deploying AspireShop, if I choose to expose catalogdbmanager publicly, I still get a 404 from the deployed application after browsing to /health.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#188]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 3 [ Includes Aspire 8.0.0-preview.5.24201.12 and SDK 8.0.300-preview.24203.14 ]
3. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone aspire-samples repo, checkout the `preview.5` branch
2. Update sdk version to 8.0.300-preview.24203.14 in global.json
3. Open samples\AspireShop.sln
4. Build and run
5. Open Program.cs under AspireShop.AppHost, add following code to expose 'catalogmanager'
    - ![image](https://github.com/dotnet/aspire-samples/assets/71361488/74dcb382-f3ec-47e0-aeac-8409fe5d9da5)
6. Open the solution folder in a Command Prompt
7. Run `azd init` to initialize the app for deployment
8. Run `azd up` to deploy to Azure, you can see that catalogdbmanager and frontend are available publicly (i.e. there's no 'internal' in the URL)
    - ![image](https://github.com/dotnet/aspire-samples/assets/71361488/8c27910e-7877-4c23-a21a-49d579a98517)

**ACTUAL**

Catalogdbmanager fails to load when browsing to /health
![image](https://github.com/dotnet/aspire-samples/assets/71361488/0298192a-dc09-4e4c-aa6f-1e8f14a75f98)

**Note**

1. But when you running it, if you click the Endpoint for 'catalogdbmanager' in the dashboard, you can see the status is 'Healthy'

    - ![image](https://github.com/dotnet/aspire-samples/assets/71361488/3acec171-95de-4246-9be1-c1b6ab05cac2)

**EXPECTED**

I can get status as 'Healthy' when I hit the Endpoint of the deployed catalogdbmanager.

**Comment by davidfowl** [comment]
What version of azd?

**Comment by v-sherryfan** [comment]
@davidfowl The azd version is 1.8.0.

**Comment by DamianEdwards** [comment]
The health endpoints are no longer added in Production environments so the 404 is expected after deployment.
