### ISSUE TITLE
NuGet package versioning is hidden from sample users

### ISSUE THREAD

**Issue by yoDon** [dotnet/aspire-samples#192]
Never, ever, not in a million years, would I have thought to look for an inherited package manager versioning specifier document somewhere above the otherwise complete sample solution folder I care about. 

Please don't do "clever" things like this in sample repos.

Users, like me, are going to attempt to build their first Aspire project by copying one of the sample solutions out of this repo and pasting it into their own repo to start messing with it.

The copied sample won't work.

None of the samples will work.

Hours will be wasted, and the devs will either give up or come close to it.

**Comment by davidfowl** [comment]
cc @DamianEdwards

**Comment by DamianEdwards** [comment]
Yep agreed. We discussed this when first creating this repo but the decision was made to use central package management (CPM). Now that we're getting Dependabot configured I'll remove CPM from this repo for the reasons you cite.
