### ISSUE TITLE
Standalone dashboard not being populated per the readme

### ISSUE THREAD

**Issue by jonoabroad** [dotnet/aspire-samples#194]
This can be replicated using any of the following

- preview-4 
- preview-5
- preview-5 & PR-191

The steps were the same, from the StandaloneDashboard sample directory ( .\samples\StandaloneDashboard\) do the following:

1. run the dashboard via docker
2. run the console app
3. view the dashboard @ http://localhost:18888/ and check the the logs, metrics and traces - all were empty

I've attached the logs of the 3 runs as files as their output is quite prolific but not wildly informative to my eyes.

[preview-4-output.md](https://github.com/dotnet/aspire-samples/files/14984982/preview-4-output.md)
[preview-5-output.md](https://github.com/dotnet/aspire-samples/files/14984983/preview-5-output.md)
[preview-5-pr-191-output.md](https://github.com/dotnet/aspire-samples/files/14984984/preview-5-pr-191-output.md)

**Comment by davidfowl** [comment]
You have to set the address of the otlp endpoint in the application:

https://github.com/dotnet/aspire-samples/tree/main/samples/StandaloneDashboard#configure-opentelemetry

cc @JamesNK

**Comment by jonoabroad** [comment]
Thanks for the quick reply.

Isn't that provided out of the box?

https://github.com/dotnet/aspire-samples/blob/main/samples/StandaloneDashboard/ConsoleApp/appsettings.json#L7

**Comment by davidfowl** [comment]
Is the dashboard successfully running in docker with the ports exposed?

**Comment by jonoabroad** [comment]
Closing as I had a user environment variable set for OTEL_EXPORTER_OTLP_ENDPOINT which is why no logs were appearing. 

Thank you for your time, sorry to waste it.
