### ISSUE TITLE
[WebToolsE2E][Aspire] When running StandaloneDashboard, token authentication is required but there is no token value in cmd.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#218]
**REGRESSION INFO:** If you start a container from `mcr.microsoft.com/dotnet/nightly/aspire-dashboard : 8.0.0-preview.4`, you do not need to enter token authentication.

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 5 [ Includes Aspire 8.0.0-preview.6.24214.1 ]
3. Apply NuGet dotnet-tools Feeds
4. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone aspire-samples repo, checkout `preview.6` branch
2. Update sdk version to `8.0.300-preview.24203.14` in global.json
3. Open samples\StandaloneDashboard.sln
4. The following command starts the Aspire dashboard in a Docker container:
   - docker run --rm -it -p 18888:18888 -p 4317:18889 -d --name aspire-dashboard mcr.microsoft.com/dotnet/nightly/aspire-dashboard:**8.0.0-preview.6**
5. From the command line:
    - Navigate to the StandaloneDashboard folder
    - Run the .NET app by executing the following at the command prompt (opened to the base directory of the sample):
        - dotnet run --project ConsoleApp
6. View the Aspire dashboard at http://localhost:18888 to see app telemetry

**ACTUAL:**

If you start the container from `mcr.microsoft.com/dotnet/nightly/aspire-dashboard : 8.0.0-preview.6`, you need to enter token authentication, but the cmd does not contain any token value
![image](https://github.com/dotnet/aspire-samples/assets/71361488/f36d0c29-710b-4fc5-9d31-00ae27358f4e)
![image](https://github.com/dotnet/aspire-samples/assets/71361488/64f5e2e7-e2e4-4c0a-a154-d56d4cd8e3a9)

**EXPECTED**

CMD should include token value then you can login successfully as follows
![image](https://github.com/dotnet/aspire-samples/assets/71361488/8dff349e-fb38-4937-ba2e-1dfbf8a7c2a2)

**Comment by DamianEdwards** [comment]
@JamesNK can you take a look please?

**Comment by JamesNK** [comment]
Everything is working correctly, but perhaps docs should be improved to reduce this confusion.

In standalone mode the dashboard is being run in a container. It prints its console logs to the container host, i.e. Docker

![image](https://github.com/dotnet/aspire-samples/assets/303201/bff2fdd4-8693-4f72-b830-0e33356415eb)

The console app in this sample has nothing to do with Aspire (other than sending it telemetry) so won't have a login token.

To login, copy the token (highlighted) from container logs into the dashboard login screen and then login to view data:

![image](https://github.com/dotnet/aspire-samples/assets/303201/fc4d117f-7566-4cfd-8069-333cbe87de9f)
