### ISSUE TITLE
[WebToolsE2E][Aspire] After successfully deploying the solution Metrics, the `app` container app status is Failed:appContainerCrashing.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#261]
**REGRESSION INFO:** Also repro on Aspire 8.0 P6

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 7 [ Includes Aspire 8.0.0-preview.7.24251.11 and SDK 8.0.300-preview.24203.14 ]
3. Apply NuGet dotnet-tools Feed
4. Install Docker Desktop for Windows
5. Install latest azd [1.9.0-beta.1-daily.3760115]

**REPRO STEPS**

1. Clone aspire-samples repo, checkout the `release/8.0` branch
2. Open samples\Metrics.sln
3. Build 
4. Deploy using azd
    - Open the solution folder in a Command Prompt
    - Run `azd init`, select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter
    - Run `azd up` to deploy to Azure
5. After deployment successful, open the resource group, the `app` Container App status is Failed:appContainerCrashing.

**ACTUAL**
![image](https://github.com/dotnet/aspire-samples/assets/71361488/1801b326-7bfd-4f1a-90ce-29d63095fd4a)

**EXPECTED**

The `app` Container App status is successful after deployment successful.

**Comment by vicperdana** [comment]
@v-sherryfan See this suggestion from @davidfowl [here](https://github.com/dotnet/aspire-samples/issues/201)

**Comment by v-sherryfan** [comment]
@vicperdana Thank you for your investigation. Verified this issue is not reproduced on `release/8.0` branch using VS 17.10 GA FB + azd [1.10.0-beta.1-daily.3787247]
