### ISSUE TITLE
Fail to load the service page after running "azd up" for some samples

### ISSUE THREAD

**Issue by Menghua1** [dotnet/aspire-samples#262]
**Describe the issue:**
After running the `azd up` command, click the output link, and an error occurs when loading the page. The page is as follows:
![image](https://github.com/dotnet/aspire-samples/assets/111940661/71df3689-02ec-4be6-881b-e815a984e955)

**Repro Steps:**

1. Clone code.
2. Cd to the sample folder.
3. Run command `azd init`.
4. Run command `azd up`.
5. Click the output link.

**Environment:**
- Azd version: `azd version 1.9.0-daily.3765530 (commit 651394c3ddcfadff194d177f8b0ddf06fe3752bf)`
- Aspire version: `8.0.0-preview.6.24214.1`
- Sample: [AspireShop](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireShop)(service basketservice), [AspireWithDapr](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithDapr)(service webfrontend), [AspireWithNode](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithNode)(service wearherapi), [ClientAppsIntegration](https://github.com/dotnet/aspire-samples/tree/main/samples/ClientAppsIntegration)(service apiservice), [DatabaseContainers](https://github.com/dotnet/aspire-samples/tree/main/samples/DatabaseContainers)(service apiservice), [DatabaseMigrations](https://github.com/dotnet/aspire-samples/tree/main/samples/DatabaseMigrations)(service api), [Metrics](https://github.com/dotnet/aspire-samples/tree/main/samples/Metrics)(service app), [OrleansVoting](https://github.com/dotnet/aspire-samples/tree/main/samples/OrleansVoting)(service voting-fe), [VolumeMount](https://github.com/dotnet/aspire-samples/tree/main/samples/VolumeMount)(service blazorweb), `aspire-starter`(service apiservice).
- Branch: main

**Expected behavior:**
After `azd up`, all services links can load normally.

@rajeshkamal5050, @vhvb1989 for notification.

**Comment by DamianEdwards** [comment]
I don't think it's expected you could `azd up` the entire samples repo. Each directory under the `./samples` directory is an individual Aspire app and some of them will deploy successfully with `azd` but not all as each sample generally only includes enough specific code as is required to demonstrate the topic of the sample.

**Comment by vicperdana** [comment]
Did `azd up` return any errors?  Try running `azd up --debug` to get more info.

**Comment by Menghua1** [comment]
> I don't think it's expected you could `azd up` the entire samples repo. Each directory under the `./samples` directory is an individual Aspire app and some of them will deploy successfully with `azd` but not all as each sample generally only includes enough specific code as is required to demonstrate the topic of the sample.

Maybe my description is not clear enough. What I want to express is that for some projects in the `./samples` directory, after running `azd up`, an error occurs on the page loading the service.

**Comment by Menghua1** [comment]
> Did `azd up` return any errors? Try running `azd up --debug` to get more info.

More log info is as follows:
![image](https://github.com/dotnet/aspire-samples/assets/111940661/9279c979-a42d-4408-982b-db90ef448fed)
![image](https://github.com/dotnet/aspire-samples/assets/111940661/7675faab-763c-4f7b-bcb6-219eac70c3be)

**Comment by vicperdana** [comment]
So all deployed successfully?  Hard to say from the screenshots.

**Comment by Menghua1** [comment]
> So all deployed successfully? Hard to say from the screenshots.

Yes, the deployment is successful, and the output in the container in the picture below is also normal, but the page cannot be loaded normally. Is this an expected internal service?
![image](https://github.com/dotnet/aspire-samples/assets/111940661/40e20f59-8cb2-4958-a981-c87e9cc009fb)

**Comment by rajeshkamal5050** [comment]
@Menghua1 are you seeing this for any endpoint/service which was configured in app-host to be public but is showing 404/stopped? Suspecting you are seeing this page 404/stopped page for internal endpoints/services. Which is the right behavior.

**Comment by Menghua1** [comment]
> 404/stopped page



> @Menghua1 are you seeing this for any endpoint/service which was configured in app-host to be public but is showing 404/stopped? Suspecting you are seeing this page 404/stopped page for internal endpoints/services. Which is the right behavior. ex:
> 
> > starter-redis
> > Services:
> > apiservice  https://apiservice.internal.braveflower-4335e738.eastus.azurecontainerapps.io/ - 404/stopped
> > cache  https://cache.internal.braveflower-4335e738.eastus.azurecontainerapps.io/ - 404/stopped
> > webfrontend  https://webfrontend.braveflower-4335e738.eastus.azurecontainerapps.io/ - accessible

Yes, all 404/stopped pages are configured with app-host as `internal`, since this is expected I will close this issue.
