### ISSUE TITLE
[WebToolsE2E][Aspire] Even though I have applied the feed of sdk 8.0.300, deploying AspireWithNode/AspireWithDapr still fails: Unable to find package Microsoft.NETCore.App.Host.linux-x64 with version (= 8.0.5).

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#270]
**REGRESSION INFO:** Worked fine on VS 17.10 GA [34908.272.d17.10] + 1.10.0-beta.1-daily.3768065 + Aspire 8.0.0 (older machine)

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 GA[34910.138.d17.10] [ Includes Aspire 8.0.0 and SDK 8.0.300 ]
3. Apply NuGet darc-pub-dotnet-aspire Feed
4. Install sdk 8.0.300 feed
5. Install cred helper
6. Install Docker Desktop for Windows
7. Install latest azd [1.10.0-beta.1-daily.3780018]
8. Install Node.js

**REPRO STEPS**

1. Clone aspire-samples repo, checkout the `release/8.0` branch
2. Open samples\AspireWithNode.sln
3. Build 
4. Deploy using azd
    - Open the solution folder in a Command Prompt
    - Run `azd init`, select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter
    - Run `azd up` to deploy to Azure

**ACTUAL**
error NU1102: Unable to find package Microsoft.NETCore.App.Host.linux-x64 with version (= 8.0.5)
error NU1102:   - Found 158 version(s) in nuget.org [ Nearest version: 9.0.0-preview.1.24080.9 ]
error NU1102:   - Versions from aspire-stable were not considered
![image](https://github.com/dotnet/aspire-samples/assets/71361488/1d303478-48b0-41dc-916a-a60adc23e1cf)

**Note**

- Both AspireWithNode and AspireWithDapr solutions reproduce this issue. (Note: I have applied sdk 8.0.300 feed and added PAT token)

**EXPECTED**
![image](https://github.com/dotnet/aspire-samples/assets/71361488/63aa3afa-096a-4732-8e5f-d247b70ebaf7)

**Comment by balachir** [comment]
@v-sherryfan for this machine, can you confirm if you applied the 8.0.5 feed? From the error message, I believe that's required too.

cc: @v-elenafeng

**Comment by balachir** [comment]
Actually, I just realized that you have a note in ACTUAL saying that you did apply the 8.0.300 feed.

**Comment by DamianEdwards** [comment]
The error message doesn't indicate that the 8.0.300 feed has been applied which is curious. I only see that nuget.org and the stable aspire feed were looked in. Can you share details of all feeds configured and how (global vs. nuget.config, etc.).

**Comment by v-sherryfan** [comment]
@balachir Yes, I did add the sdk 8.0.300 feed, this step was missing from the INSTALL STEPS and has been added. And Elena also helped me verify this issue and she also reproduced it. 
@DamianEdwards @joperezr Here are all the feeds added and the PAT token made on the machine where I reproduced the issue, please help check.
![image](https://github.com/dotnet/aspire-samples/assets/71361488/0cd3f401-fed3-41d4-9450-7220eaad59c1)

**Comment by v-sherryfan** [comment]
@DamianEdwards @joperezr  Here are all the feeds added and the PAT token made on the machine where I reproduced the issue, please help check.
![image](https://github.com/dotnet/aspire-samples/assets/71361488/e0dedc33-8fdd-4376-baa5-838e58a7e409)
cc: @balachir

**Comment by v-sherryfan** [comment]
Not repro on VS 17.10 GA FB + latest daily azd [1.10.0-beta.1-daily.3787247]
![image](https://github.com/dotnet/aspire-samples/assets/71361488/f852a629-cc6c-4fc3-8e2c-499fee6a20a3)

**Comment by v-sherryfan** [comment]
Closed it as fixed.
