### ISSUE TITLE
[WebToolsE2E][Aspire] Failed to starts the Aspire dashboard in a Docker container with the aspire-dashboard:8.0.0

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire-samples#278]
**REGRESSION INFO**: Work in aspire-dashboard:8.0.0-preview.7

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 GA [rel.d17.10-34916.146] (including Aspire 8.0.0)
3. Apply NuGet dotnet-tools Feeds
4. Install Docker Desktop for Windows

**REPRO STEPS**
1. Clone aspire-samples repo, checkout the `release/8.0` branch
2. Update sdk version to 8.0.300 in global.json
3. Open samples\StandaloneDashboard.sln
4. Run the following command starts the Aspire dashboard in a Docker container:
`docker run --rm -it -p 18888:18888 -p 4317:18889 -d --name aspire-dashboard mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0`

**ACTUAL**:
![Screenshot 2024-05-17 110636](https://github.com/dotnet/aspire-samples/assets/88122107/5a336f87-5919-4ea5-9ad6-7f0c01c71b91)

**Error Log**
```
Unable to find image 'mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0' locally
docker: Error response from daemon: manifest for mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0 not found: manifest unknown: manifest tagged by "8.0.0" is not found.
See 'docker run --help'.
```

**Comment by Rita003** [comment]
According to https://mcr.microsoft.com/en-us/product/dotnet/aspire-dashboard/tags, the latest aspire-dashboard is 8.0.0-preview.7, unable to find 8.0.0 aspire-dashboard, IS this issue as by design?

**Comment by DamianEdwards** [comment]
@Rita003 I think so, that version hasn't been pushed yet.

**Comment by DamianEdwards** [comment]
This is out of date now as the GA image was pushed.
