### ISSUE TITLE
Show composing a Python app into AppHost as a resource

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire-samples#3]
Scenario:
- ASP.NET Core API frontend (e.g. Blazor SSR)
- Python (e.g. FastAPI) backend
- Frontend talks to the backend
- Backend talks to a PostgreSQL database
- Both apps should be composed into AppHost project so that service endpoint from backend is injected into environment of frontend
- Backend should have connection string of database injected into environment variables

**Comment by thangchung** [comment]
+1 for this polyglot programming language combination model.

**Comment by goldytech** [comment]
@DamianEdwards Is this sample available now?

**Comment by DamianEdwards** [comment]
@goldytech no we'll wait until dotnet/aspire#4142 goes in before adding this sample.

**Comment by goldytech** [comment]
@DamianEdwards Thanks for sharing this update. I'm looking forward to it in version 8.1!
