### ISSUE TITLE
eShopLite Sample: needs to run migrations

### ISSUE THREAD

**Issue by giggio** [dotnet/aspire-samples#32]
Running the app will result in errors. In the log you get `database "catalogdb" does not exist`.
Either the docs are missing something, or the tooling has a bug.

**Comment by DamianEdwards** [comment]
The eShopLite sample includes a project dedicated to [running database migrations](https://github.com/dotnet/aspire-samples/blob/main/samples/eShopLite/eShopLite.CatalogDb/Program.cs). When you launch the AppHost project, the CatalogDb project will be launched and perform database initialization and migration. There is no coordination of resource launch order though so it's always possible the DB container isn't up yet by the time the CatalogDb init logic runs, but it should be retrying.

Can you share the full logs from the eShoptLite.CatalogDb project when you've launched it?

**Comment by giggio** [comment]
@DamianEdwards it worked now, I'm not sure it didn't before.
Maybe there is a race going on, but I can't repro anymore. Feel free to close if you understand that it is a minor detail.

**Comment by DamianEdwards** [comment]
It's definitely possible that the retry logic could exhaust all retries before the db container has fully spun-up, and in that case the database would never get initialized. We could look at updating the sample to have longer timeouts or more retries to make it less likely but seems fine to close this for now and we can reinvestigate if we get more reports of it.
