### ISSUE TITLE
Running the DatabaseContainers sample fails on startup of SQL Server.

### ISSUE THREAD

**Issue by keberle** [dotnet/aspire-samples#343]
Just to make sure I removed as many variables as possible:

- Brand new Surface Copilot+ laptop
- Fresh install of Visual Studio 2022 Preview
- Fresh install of Docker
- WSL Updated

When starting up the DatabaseContainers sample DatabaseContainers.AppHost, I get the following:

```
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 8.0.1+a6e341ebbf956bbcec0dda304109815fcbae70c9
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: C:\Users\kylee\source\github\aspire-samples\samples\DatabaseContainers\DatabaseContainers.AppHost
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: https://localhost:17007
info: Aspire.Hosting.DistributedApplication[0]
      Login to the dashboard at https://localhost:17007/login?t=8224af4215096bf04cb166595c08a39b
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
fail: Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0]
      could not determine host address and port for container port      {"Container": {"name":"sqlserver"}, "Reconciliation": 13, "error": "container '/sqlserver-20hgcs8' is not running: exited"}
fail: Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0]
      could not create Endpoint object  {"Container": {"name":"sqlserver"}, "Reconciliation": 13, "ServiceName": "sqlserver", "Workload": "/sqlserver", "error": "container '/sqlserver-20hgcs8' is not running: exited"}
```
      
I'll continue poking around and update this issue if I run into the solution or a workaround but adding the issue here in case anyone else is searching for it.

**Comment by kyle-vixolink** [comment]
Attempts to install MSSQL 2022 or the Cosmos DB Emulator have also failed.  (Aspire apps using cosmos emulator failed too)

Based on the errors, its looking like some of these features aren't quite ready for Microsoft Surface Copilot+ Windows 11 machines as the Windows ARM 64 support for them isn't quite there.  If I get some free time, I'll try to find other ways to work around this problem but I am at least updating this issue in case someone is searching and runs into the same thing.

**Comment by DamianEdwards** [comment]
SQL Server does not work on Windows for ARM as yet.

**Comment by keberle** [comment]
Yeah, I have now found a few things that don't seem to be Windows ARM compatible just yet.  I really like the performance of the Copilot+ machine but the compatibility gaps are making it a little frustrating for software development.

Thank you for getting back to me.
