### ISSUE TITLE
[WebToolsE2E][Aspire] Opening the HealthChecksUI solution fails with error: Unable to find package AspNetCore.HealthChecks.UI.Client with version (>= 8.1.0-preview.1.24360.8) from dotnet8feed.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#373]
**REGRESSION INFO:** Worked in `main` branch [Aspire 8.0.1] and `aspire/main` branch [Aspire 8.1.0-preview.1.24325.6]

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10.5 [ Includes Aspire 8.0.0 ]
3. Install Aspire 8.1 [8.1.0-preview.1.24365.6]
4. Apply NuGet dotnet8 Feeds
5. Install Docker Desktop for Windows
6. Install the latest released azd [1.9.5]

**REPRO STEPS**

1. Clone aspire-samples repo, checkout `aspire-8.1` branch
2. Open HealthChecksUI.sln

**ACTUAL:**
NU1102	Unable to find package AspNetCore.HealthChecks.UI.Client with version (>= 8.1.0-preview.1.24360.8)
Found 29 version(s) in nuget.org [ Nearest version: 8.0.1 ]
Found 0 version(s) in dotnet8feed
Versions from C:\Program Files\dotnet\library-packs were not considered	

- Even manually updating the package version to the latest version will fail with this error

![image](https://github.com/user-attachments/assets/23ea887a-bdc5-4aa4-bdba-c175380b93f0)

![image](https://github.com/user-attachments/assets/8e17d286-fd66-4797-9664-b15d91467b4d)

**EXPECTED**
 
Opening solution without any errors.

**Comment by balachir** [comment]
@mitchdenny @DamianEdwards it seems like a feed issue. Can you investigate, please?

**Comment by mitchdenny** [comment]
This should be fixed now.

**Comment by v-elenafeng** [comment]
Checked this issue using VS 17.10.4 and Aspire 8.1 candidate, no repro.

**Comment by balachir** [comment]
@v-elenafeng thanks for verifying. Closing this issue as it doesn't reproduce for Elena anymore.
