### ISSUE TITLE
eshoplite project dotnet publish error: 

### ISSUE THREAD

**Issue by LianwMS** [dotnet/aspire-samples#39]
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: D:\cupertino\aspire-samples\samples\eShopLite\eShopLite.CatalogDb\appsettings.De
velopment.json, D:\cupertino\aspire-samples\samples\eShopLite\eShopLite.CatalogService\appsettings.Development.json, D:\cupertino\aspire-samples\samples\eShopLite\eShopLite.CatalogDb\appsettings.json, D:\cupertino\aspire-samples\samples\eShopLite\eShopLite.CatalogService\appsett
ings.json. [D:\cupertino\aspire-samples\samples\eShopLite\eShopLite.CatalogService\eShopLite.CatalogService.csproj]

It seems that both db and service project have appetting file. and output to the same folder/

**Comment by davidfowl** [comment]
What project did you publish?

**Comment by LianwMS** [comment]
I just dotnet publish under the folder contains sln follow the guide:

 Publish the solution projects to ACR using the dotnet publish command in the solution directory:

# In the solution directory
dotnet publish -r linux-x64 --self-contained -p:PublishProfile=DefaultContainer -p:ContainerRegistry=$loginServer

**Comment by LianwMS** [comment]
I also see a proj about catalogdb. In guide, I do not see the deployment step about that proj.

**Comment by davidfowl** [comment]
@DamianEdwards this project errors when you deploy

**Comment by DamianEdwards** [comment]
Hmm I remember hitting this and can't recall how I fixed it or why it's not fixed here. I know the cause, will have to investigate. Odd that we haven't hit this earlier as part of the AZD development.
