### ISSUE TITLE
AspireShop deploys to Azure in broken state

### ISSUE THREAD

**Issue by ericziko** [dotnet/aspire-samples#433]
# AspireShop bug report

**User Story**
As a software engineer trying out the AspireShop sample, I expect that when I deploy to Azure using the `azd init` and `azd up` commands that the sample be deployed to azure in complete working order.

**Bug Description:** 
I pulled down the aspire-samples and tried to deploy the AspireShop web site to azure using `azd init` and `azd up` - the only material changes I made to the application was setting up instrumentation for App Insights. The **basketcache** and **catalog** and **catalogdbmanager** services are all broken. Please see the following screenshshots and information below for help in diagnosing and troubleshooting this.

## Redis Error Message
```
The message timed out in the backlog attempting to send because no connection became available (5000ms) - Last Connection Exception: UnableToConnect (None, 0-read, last-recv: 0) on basketcache:6379/Interactive, Flushed/ReadAsync, last: ECHO, origin: ResetNonConnected, outstanding: 12, last-read: 5s ago, last-write: 4s ago, unanswered-write: 5s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.8.0.27420, command=GET, timeout: 5000, inst: 0, qu: 0, qs: 12, aw: False, bw: CheckingForTimeout, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, last-in: 0, cur-in: 0, sync-ops: 0, async-ops: 29, serverEndpoint: basketcache:6379, conn-sec: 56, aoc: 0, mc: 1/1/0, mgr: 10 of 10 available, clientName: basketservice--76q7go8-557676c66f-8f7ml(SE.Redis-v2.8.0.27420), IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=0,Free=32767,Min=4,Max=32767), POOL: (Threads=4,QueuedItems=0,CompletedItems=5147,Timers=9), v: 2.8.0.27420 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) UnableToConnect (None, 0-read, last-recv: 0) on basketcache:6379/Interactive, Flushed/ReadAsync, last: ECHO, origin: ResetNonConnected, outstanding: 12, last-read: 5s ago, last-write: 4s ago, unanswered-write: 5s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.8.0.27420 
```

## Broken containers screenshot 

![image](https://github.com/user-attachments/assets/46b5b7d1-56eb-4016-aa06-46a320eb3ba9)

## Azure App Insights screenshot

![image](https://github.com/user-attachments/assets/f075e71c-c872-4b80-82d9-5f289f257bdd)

**Comment by v-sherryfan** [comment]
This issue also repro on AspireWithDapr sample using VS 17.12 Preview 4 + Aspire 9.0.0.
