### ISSUE TITLE
Fail to run `azd init` for all samples except the sample `StandaloneDashboard`

### ISSUE THREAD

**Issue by Menghua1** [dotnet/aspire-samples#440]
**Describe the issue:**
For aspire samples, run the `azd init` command failed and the error message is as follows:
![image](https://github.com/user-attachments/assets/5851a7d2-9934-4071-aca3-0dcadd764ada)

**Repro Steps:**
1. Clone code.
2. Run command `cd samples/Aspirewithdapr`.
3. Run command `azd init`.

**Environment:**

- Azd version: `azd version 1.10.0-beta.1-daily.4077837 (commit a17935e47211ed01780281974c6d63b467de5b14)`.
- Aspire version: `8.2.0/8.0.100`.
- Sample: [AspireShop](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireShop), [AspireWithDapr](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithDapr), [AspireWithJavaScript](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithJavaScript), [AspireWithNode](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithNode), [AspireWithPython](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireWithPython), [ClientAppsIntegration](https://github.com/dotnet/aspire-samples/tree/main/samples/ClientAppsIntegration), [ContainerBuild](https://github.com/dotnet/aspire-samples/tree/main/samples/ContainerBuild), [DatabaseContainers](https://github.com/dotnet/aspire-samples/tree/main/samples/DatabaseContainers), [DatabaseMigrations](https://github.com/dotnet/aspire-samples/tree/main/samples/DatabaseMigrations), [HealthChecksUI](https://github.com/dotnet/aspire-samples/tree/main/samples/HealthChecksUI), [Metrics](https://github.com/dotnet/aspire-samples/tree/main/samples/Metrics), [OrleansVoting](https://github.com/dotnet/aspire-samples/tree/main/samples/OrleansVoting), [Shared](https://github.com/dotnet/aspire-samples/tree/main/samples/Shared), [VolumeMount](https://github.com/dotnet/aspire-samples/tree/main/samples/VolumeMount).
- Branch: main.

**Expected behavior:**
`azd init` command can be executed successfully.

@rajeshkamal5050, @vhvb1989 for notification.

**Comment by rajeshkamal5050** [comment]
Should be fixed with this - https://github.com/dotnet/aspire-samples/pull/443

**Comment by v-xuto** [comment]
> Should be fixed with this - [Update to .NET Aspire 8.2.0](https://github.com/dotnet/aspire-samples/pull/443)

Verifying.

**Comment by Menghua1** [comment]
@rajeshkamal5050 The current issue has been fixed and we will close it.
In addition, based on the latest code test, we have opened two new issues: https://github.com/dotnet/aspire-samples/issues/451, https://github.com/dotnet/aspire-samples/issues/452.
