### ISSUE TITLE
Fail to run `azd up` for sample `ContainerBuild`

### ISSUE THREAD

**Issue by Menghua1** [dotnet/aspire-samples#452]
**Describe the issue:**
For `ContainerBuild` sample, run the `azd up` command failed and the error message is as follows:
![image](https://github.com/user-attachments/assets/2456caf9-d3a1-4960-b420-0fe87cfcbdef)

**Repro Steps:**
1. Clone code.
2. Run command `cd samples/AspireWithPython`.
3. Run command `azd init`.
4. Run command `azd up`.

**Environment:**

- Azd version: `azd version 1.10.0-beta.1-daily.4077837 (commit a17935e47211ed01780281974c6d63b467de5b14)`.
- Aspire version: `8.2.0/8.0.100`.
- Sample: [ContainerBuild](https://github.com/dotnet/aspire-samples/tree/main/samples/ContainerBuild).
- Branch: main.

**Expected behavior:**
`azd up` command can be executed successfully.

@rajeshkamal5050, @vhvb1989 for notification.

**Comment by Menghua1** [comment]
@rajeshkamal5050, @vhvb1989  In the latest round of azd manual testing, this issue still exists.

- Azd version: azd version 1.11.0-beta.1-daily.4152592 (commit e2ff8ba7dcc5b3f7e883213a2315a8b275294def).
- Aspire version: `8.2.1/8.0.100`.
- Sample: [ContainerBuild](https://github.com/dotnet/aspire-samples/tree/main/samples/ContainerBuild).
- Branch: main.

**Comment by DamianEdwards** [comment]
Wasn't able to reproduce this with latest azd 1.10.x release and was able to run `azd up` without error. That said, I'm making some improvements to the sample WRT deployability in #532
