### ISSUE TITLE
Create new samples for Aspire + Azure Functions integration

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspire-samples#519]
Ahead of the upcoming release of preview support for Aspire and Azure Functions, we'll want to include a sample of the integration in this repo.

There are probably two canonical Functions examples that we might want to include here:

- Using HTTP triggers to implement a web hook
- Implementing a web-queue-worker scenario using a Minimal API service and an Azure Storage Queue or Azure Service Bus trigger

Along the way, we'll want to showcase the following features of the integration:

- Support for `AddServiceDefaults` with the new Functions minimal builder
- Support for Aspire-injected resources (show uploading something to an Azure Storage Blob via the injected `BlobServiceClient`)
- Support for service discovery with Functions HTTP triggers

**Comment by DamianEdwards** [comment]
This was completed.

**Comment by mkercheval-tva** [comment]
Thanks, @captainsafia and @DamianEdwards. The example is a great starting point, but we believe it can be improved.

We need all functions to run using HTTPS, and we currently use the following command for local testing and development:
```sh
func start --useHttps --cert $filePath --password $certPassword --verbose --dotnet-isolated-debug
```

However, the --useHttps flag does not work as expected ([reference](https://stackoverflow.com/questions/62453695/how-to-enable-azure-function-https-easily-when-do-local-test)).

We have tried passing arguments in launchSettings.json without success. Using AddExecutable with a custom PowerShell script works, but we lose tracing and can't easily access the function's URL from Aspire’s API.

Running without HTTPS works, but our local clients require HTTPS to connect to the function apps. A working example that enables HTTPS while maintaining Aspire’s tracing and service discovery would greatly help us move forward with Aspire.
