### ISSUE TITLE
[WebToolsE2E][Aspire] When running DatabaseMigrations solution, the migration project shows no longer running in dashboard.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#526]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.12 Preview 4
3. Install Docker Desktop
4. Install azd [1.10.3]

**REPRO STEPS**

1. Clone aspire-samples repo and open DatabaseMigrations.sln
2. F5 and go to dashboard

**ACTUAL**
The migration project shows no longer running
![Image](https://github.com/user-attachments/assets/63d3dd42-52b4-4802-9505-b31aed77a7ec)

**NOTE**

- This issue also repro on aspire-samples 9.0.0

**EXPECTED**
Migrations are running like any other project

**Comment by DamianEdwards** [comment]
The migrations project in that sample is a console app that runs to completion so this is expected. It runs migrations and then exits.
