### ISSUE TITLE
[WebToolsE2E][Aspire] Building version 9.0.0 of AspireWithPython fails with an error: " 'Aspire.Hosting.PythonAppResourceBuilderExtensions.AddPythonApp()' is for evaluation purposes only and is subject to change or removal in future updates."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#527]
**REGRESSION INFO:** worked in `main` branch [Aspire 9.0.0 rc 1]

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.12 Preview 4
3. Install Python [3.13.0]
4. Install Docker Desktop
5. Install azd [1.10.3]

**REPRO STEPS**

1. Clone aspire-samples repo, checkout to `UpdateTo9GA` branch
2. Add aspire 9.0.0 feed/mapping to nuget.config
3. Open samples\AspireWithPython and build

**ACTUAL**
'Aspire.Hosting.PythonAppResourceBuilderExtensions.AddPythonApp(Aspire.Hosting.IDistributedApplicationBuilder, string, string, string, params string[])' is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
![Image](https://github.com/user-attachments/assets/8c20e2bd-6806-4ece-87be-d35021fe1fd1)

**NOTE**

- This issue does not reproduce on aspire-samples `main` branch [Aspire 9.0.0 rc 1]

**EXPECTED**
Building project without any errors.

**Comment by davidfowl** [comment]
This is by design, we marked the API as experimental in Aspire 9 because it's unfinished. See https://github.com/dotnet/aspire/issues/6298

**Comment by davidfowl** [comment]
@DamianEdwards we should update the sample to ignore the warning in source.

**Comment by DamianEdwards** [comment]
When the samples are updated for 9.0 GA, we will 😄

**Comment by DamianEdwards** [comment]
Fixed

**Comment by v-sherryfan** [comment]
Not repro on main branch
