### ISSUE TITLE
How to Aspire with 100s of services, Executables?

### ISSUE THREAD

**Issue by jkears** [dotnet/aspire-samples#59]
When creating an Aspire app host, I following this logic ...  
`builder.AddProject<Projects.NextWare_UI_Builder_EditServices_API>("nextwareuibuildereditservices");`

For this I need to add a project reference to the **NextWare_UI_Builder_EditServices_API** project in the Aspire AppHost.

Does that mean that our Aspire AppHost project would need to have a project dependency on each of the 100+ service projects or is there another way to configure this?  

And, what is meant by executables in the Dashboard?

**Comment by DamianEdwards** [comment]
In the next preview you'll be able to add projects without a project reference, by passing a path to a project file.

Executables can be composed in as resources to be launched by the AppHost, e.g. that's how the Node sample in this repo works, by running `npm start`.

**Comment by jkears** [comment]
@DamianEdwards and @davidfowl many thanks!

I think paths to each separate project file would be ideal, and by path I hope you mean Git path and File path??    Git support would be ideal, at least for our needs.    

We have developed our own in-house DDD-based, Domain Modeling tool (screen shot below).  This tool includes a VS Code Ext. that we utilize to capture and model any business domain as Aggregates within Bounded Contexts (Services), complete with Command and Event definitions, Value Objects, Enums, all of which gets code generated into backing services via Rosslyn code-gen.  

We publish every model into a separate  Meta-Model registry service.  this is so that within other domain models we can establish related references to Aggregates situated within external services outside of the domain being modeled.  

We code generate REST, gRPC and GraphQL, the later of which participates within a GraphQL Gateway service, that composes across a myriad of these generated services.   

The model below is from our UI Editor services project.  We are building an App Builder for Blazor and the aggregate showing is used to import 3rd party Blazor component libraries.  

![image](https://github.com/dotnet/aspire-samples/assets/1290937/c15b8a2a-091c-4805-b395-9110a5a290f1)

We code-generate Dapr integrations, and deploy to ACA.  We use GitHub Actions to trigger build/test upon check-in.  

We used Tye extensively,  and thus further code-generate a Tye.yml file that contains all of the services within a given domain model which allows us to spin up each as named services, and hoping to replace with Aspire.   

The GraphQL Gateways utilize Redis to synchronize the GraphQL Schema for each service, and we register both Core services and Application services using **Named** HTTP Clients, one per each service as per this code-generated sample ... 

```
/// <summary>
///
/// CoreServicesEndPointConfiguration.cs
/// 
/// Generates a endpoint for each core domain service  
/// 
/// 
/// *****************************  Warning  ********************************
/// 
/// Do not modify the contents of this file! Any changes made to this file 
/// will be deleted upon next code generation.  
/// 
/// ************************************************************************
/// 
/// 
/// </summary>
/// 
namespace NextWare.UI.Builder.EditServices.API.DependencyInjection
{
    public static class CoreServicesEndPointConfiguration
    {
        public static IServiceCollection AddEndPointsCoreServices(this IServiceCollection services, ConfigurationManager configuration)
        {
            services.AddHttpClient(WellKnownCoreServicesSchemaNames.AuthorizationServices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.AuthorizationServices}/graphQL");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownCoreServicesSchemaNames.MetaModelServices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.MetaModelServices}/graphQL");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownCoreServicesSchemaNames.ValidationServices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.ValidationServices}/graphQL");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownCoreServicesSchemaNames.BusinessRuleDefinitionServices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.BusinessRuleDefinitionServices}/graphQL");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownCoreServicesSchemaNames.ReactionPolicyServices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.ReactionPolicyServices}/graphQL");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownCoreServicesSchemaNames.WorkFlowServices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.WorkFlowServices}/graphQL");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownCoreServicesSchemaNames.GatewayServices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.GatewayServices}/graphQL");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownCoreServicesSchemaNames.ACLServices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.ACLServices}/graphQL");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownCoreServicesSchemaNames.CICDServices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.CICDServices}/graphQL");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            return services;
        }
    }
}
```
With respect to GraphQL Gateways, our Gateway generator, integrates with our Meta Model Services to retrieve all service definitions, that as the user selects, generate into a separate gateway project/solution service.  

Below is and example of a Gateway that was derived from some of our ERP services to compose a GraphQL Gateway service for ERP services...

```
/// <summary>
///
/// EndPointConfiguration.cs
/// 
/// Generates a endpoint for each domain service in domain model for GraphQL Gateway
///
/// 
/// *****************************  Warning  ********************************
/// 
/// Do not modify the contents of this file! Any changes made to this file 
/// will be deleted upon next code generation.  
/// 
/// ************************************************************************
/// 
/// 
/// </summary>
/// 
namespace NextWare.Gateway.DependencyInjection
{
    public static class EndPointConfiguration
    {
        public static IServiceCollection AddEndPoints(this IServiceCollection services, ConfigurationManager configuration)
        {
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpafchatservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpafchatservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpafcommonservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpafcommonservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpafdocumentmgmtservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpafdocumentmgmtservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpaferpexternalservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpaferpexternalservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpafintegrationservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpafintegrationservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpafmetadatamodelservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpafmetadatamodelservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpbpapprovalroutingservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpbpapprovalroutingservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpbpbusinessprocessservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpbpbusinessprocessservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpbpdiagramservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpbpdiagramservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpbpreportingservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpbpreportingservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpbpsupportservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpbpsupportservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpecomdeliveryservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpecomdeliveryservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpecominventoryservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpecominventoryservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpecominvoiceservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpecominvoiceservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpecomorderservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpecomorderservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpecomorgmgmtservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpecomorgmgmtservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpecompaymentservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpecompaymentservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpecomstoreservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpecomstoreservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpftabcmgmtservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpftabcmgmtservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpftdimensionservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpftdimensionservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpftfixedassetsservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpftfixedassetsservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpftgeneralledgerservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpftgeneralledgerservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpftgrcservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpftgrcservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpfttaxservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpfttaxservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpfttransactionservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpfttransactionservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerphrcareermgmtservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerphrcareermgmtservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerphremployeeservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerphremployeeservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerphrhumanresourceservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerphrhumanresourceservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerphrpayrollservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerphrpayrollservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpkmknowledgemgmtservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpkmknowledgemgmtservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpkmresearchservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpkmresearchservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpplmindustryservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpplmindustryservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpplmproductlinemgmtservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpplmproductlinemgmtservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpplmstrategicmgmtservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpplmstrategicmgmtservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpproppropertymgmtservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpproppropertymgmtservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerppurchpurchaseservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerppurchpurchaseservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpsalescmsservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpsalescmsservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpsalescrmservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpsalescrmservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpsalesmarketingservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpsalesmarketingservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpsalespointofsaleservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpsalespointofsaleservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpsalessalesservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpsalessalesservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            services.AddHttpClient(WellKnownSchemaNames.nextwareerpsalessubscriptionservices, c =>
            {
                c.BaseAddress = new Uri($"http://{WellKnownSchemaNames.nextwareerpsalessubscriptionservices}");
            }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
            return services;
        }
    }
}
```

I have yet to review your Dapr sample in depth, but I am hoping that since we already adopted a similar end-point naming approach, and are using Dapr, that we won't have too much trouble refactoring our code-generation solution to support Aspire.  

BTW, I am in love with the tracing and metrics... WOW!!!

I am having one issue that I am trying to track down.   When I add a reference to one other API project (code-generated so these are similar in nature), I am getting a port (5001), already in use exception.   I noticed Scott's AZ Demo that we can turn generate synthetized BICEP files, showing the deployment configurations.  

Are there similar hidden commands that we can run to determine in my case where this duplicate port issue is originating from?

For example, the following Aspire viewed/captured error (below), is occurring because I am not including our Reaction Policy Service,  which the service that is running attempts to connect with to retrieve Service Bus Event subscription and publications for that given service, however when I include that service or any other service, I get that 5001 exception.  

![image](https://github.com/dotnet/aspire-samples/assets/1290937/1c3d146f-9ca6-4ac7-9235-ccef98cfc31d)

**Comment by davidfowl** [comment]
Do these projects have a launchSettings? If they don't and they are ASP.NET Core projects, they will fallback to binding to 5000 by default. If you look at the dashboard, what is under Endpoints for each of those projects?

**Comment by jkears** [comment]
@davidfowl  yes, there are launchSettings shown below... however no endpoints are showing up...

![image](https://github.com/dotnet/aspire-samples/assets/1290937/737a96e8-e218-45c9-9561-ef8c680289c0)

 Exception ... 
![image](https://github.com/dotnet/aspire-samples/assets/1290937/4aa68dfa-ea88-4dd1-a308-f7a8ec28b0a2)

launchSettings as follows  


{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:55257/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "NextWare.ProjectName.DomainName.API": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:55258/"
    },
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/api/values"
    }
  }
}



{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:55257/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "NextWare.ProjectName.DomainName.API": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:55258/"
    },
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/api/values"
    }
  }
}

{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:55269/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "NextWare.ProjectName.DomainName.API": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "api/values",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:55288/"
    },
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/api/values"
    }
  }
}

**Comment by jkears** [comment]
... and for giggles, I when I run Tye  as per this ...

![image](https://github.com/dotnet/aspire-samples/assets/1290937/556f6b92-16d2-4040-939e-6693003a2963)

![image](https://github.com/dotnet/aspire-samples/assets/1290937/91c3bb40-2e21-4558-aaf9-b8700b1a8be4)

... and I do not see any references to port 5001 anywhere.  This is the exact set of services (excluding the Reaction Policy Service) which fail due to port 5001 already being defined.

**Comment by davidfowl** [comment]
It's picking the first launch profile. If you're not using IIS express, you can delete it, or you can use .WithLaunchProfile (e.g. WithLaunchProfile("NextWare.ProjectName.DomainName.API")) to pick the right one.

**Comment by jkears** [comment]
@davidfowl and @DamianEdwards 

I reviewed the Dapr sample project but am still struggling with the Dapr side of things.

I followed the sample, however I think the issue I am having relates to the manner by which we integrate with Dapr sidecars within our current framework.     

The following depicts the service composition that we currently are experimenting with, the services showing with dashes are not part of the current experiment ...

![image](https://github.com/dotnet/aspire-samples/assets/1290937/bacaf15a-b57f-4670-9207-f3fbfa6284af)

In the above diagram, we can run GraphQL queries on the Core Services GateWay that may span multiple Aggregates should they relate to one-another via Agg IDs.  The GraphQL Gateway does a great job at dispatching the correct queries to the respective aggregate locations. 

As such, we use'**Named HTTP clients**', which previously worked with Tye.  With respect to intra-messaging between services we setup Named Clients so that it works with our GraphQL service provider (HotChocolate-HC), as HC only knows of the  Named Http client, and has no idea we bridge this over dapr. 

In Tye, we would register a named client as follows ... 

```
 services.AddHttpClient(WellKnownCoreServicesSchemaNames.ReactionPolicyServices, c =>
 {
     c.BaseAddress = new Uri($"http://{WellKnownCoreServicesSchemaNames.ReactionPolicyServices}/graphQL");
 }).AddHttpMessageHandler(() => new InvocationHandler()).AddHeaderPropagation();
```
... where in this example, **WellKnownCoreServicesSchemaNames.ReactionPolicyServices**  = ' **nextwarecoreserviceseventintegrationreactionpolicyservices**'.

Please note the use of `**InvocationHandler()**`.  

This is a Dapr API that injects a Dapr side car for the given named client.   

If I assume that the name passed in becomes both the named client that HC injects, and the DaprId, AppId for the Dapr SideCar, then  the following AppHost configuration should work (as per the diagram layout above), but it does not ... 

```
var builder = DistributedApplication.CreateBuilder(args);

// Reaction Policy Services 
var reactionPolicyService =
    builder.AddProject<Projects.NextWare_CoreServices_EventIntegration_ReactionPolicyServices_API>(
        "nextwarecoreserviceseventintegrationreactionpolicyservicesapi")
    .WithDaprSidecar("nextwarecoreserviceseventintegrationreactionpolicyservices");

// GraphQL Gateway Project that spans multiple Core Services (todo: add the other Core Services aside from ReactionPolicyServices)
var coreServicesGateWay =
    builder.AddProject<Projects.NextWare_GW_Core_Services_GraphQL_Gateway>("nextwarecoreservicesgwgatewayservicesapi")
        .WithReference(reactionPolicyService)
    .WithDaprSidecar("nextwarecoreservicesgwgatewayservices");

// UI Editor Services integrates with core services gateway to query ReactionPolicyServices

var editServicesAPI = 
    builder.AddProject<Projects.NextWare_UI_Builder_EditServices_API>("nextwareuibuildereditservicesapi")
    .WithDaprSidecar("nextwareuibuildereditservices")
    .WithReference(coreServicesGateWay);

// GraphQL Gateway Project that spans Editor Services and UI Builder
builder.AddProject<Projects.NextWare_UI_Builder_GraphQLGateway>("nextwareuibuildergatewayapi")
    .WithDaprSidecar("nextwareuibuildergateway")
    .WithReference(editServicesAPI);


builder.Build().Run();
```

![image](https://github.com/dotnet/aspire-samples/assets/1290937/377e8635-d93a-4b46-a04c-f4d06c3ec152)

Questions:  

1. In Tye, we use to see a separate SideCar per each service and Tye would randomize the port for that sidecar but in the case of   'WithDaprSidecar'  extension, where is that happening?

2. Should we be creating a profile per each SideCar inside the same launchsettings of each respective service?
3. Because of how I create the Name HTTP Client, do we need the WithDaprSideCar?  

Sorry to be a pest but I feel I am super close and this would be awesome to get resolved for the community. 

Cheers
John

**Comment by jkears** [comment]
Victory is mine! 

From an running service in a back-ground task that resolves Service Bus Event subscription retrieval from another service indirect via a GraphQL Gateway service ... sweet jimmity-crickets it works!  

![image](https://github.com/dotnet/aspire-samples/assets/1290937/9684922b-1a13-4af0-9566-e08dac4cc492)

**Comment by davidfowl** [comment]
In preview2, that line will be called implicitly with any call to WithDaprSideCar 😄

**Comment by jkears** [comment]
The final V1 design that illustrates where Aspire plugs in, which is just about everywhere.

![image](https://github.com/dotnet/aspire-samples/assets/1290937/b41c199d-3f5c-4394-a195-5d5826666bec)

The trace spans tell us so what truly is happening under the covers,  provides a more comprehensive understanding of how data flows through out our apps.  

Many thanks Aspire Team, great job!
