### ISSUE TITLE
[WebToolsE2E][Aspire] Build AspireWithNode solution failed with "The call is ambiguous between the following methods or properties: ..." after updating to Aspire 8.0 preview 2

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/aspire-samples#64]
**REGRESSION INFO**: Worked fine with Aspire 8.0.0-preview.1.23557.2

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 Preview 2
3. Install Aspire Preview 2 latest build 8.0.0-preview.2.23610.1
4. Apply NuGet Feeds
5. Install node from nodejs.org

**REPRO STEPS**

1. Clone aspire-samples repo
2. Checkout preview.2 branch
3. Update NuGet.config to use the dotnet-tools feed
4. Update Directory.Packages.props to use aspire version 8.0.0-preview.2.23610.1
5. Open solution AspireWithNode.sln
6. Build solution

**ACTUAL**
Failed to build solution with error: The call is ambiguous between the following methods or properties: 'Aspire.Hosting.NodeAppHostingExtension.AddNodeApp(Aspire.Hosting.IDistributedApplicationBuilder, string, string, string, string[]?)' and 'Aspire.Hosting.NodeAppHostingExtension.AddNodeApp(Aspire.Hosting.IDistributedApplicationBuilder, string, string, string?, string[]?)'	AspireWithNode.AppHost

![image](https://github.com/dotnet/aspire-samples/assets/82028229/365b0165-a6d2-4e04-a6a4-502426c2bab0)

**EXPECTED**
Build solution successfully.

**Comment by balachir** [comment]
@v-cazhang are you sure that you switched to the preview.2 branch of the aspire-samples repo? I cannot reproduce this with preview.2 branch. You'll be able to reproduce this using main branch and if you want to fix it using current bits from main branch, you need to delete a couple of files as shown in [this commit](https://github.com/dotnet/aspire-samples/commit/330b3cb9461154ce5bd48a18ee13cebd5d2a0965).

**Comment by v-cazhang** [comment]
@balachir, yes, I did. Below are the changes I made:
![image](https://github.com/dotnet/aspire-samples/assets/82028229/2db6e9e1-ead3-4901-bb56-ab041dacf121)

![image](https://github.com/dotnet/aspire-samples/assets/82028229/03560e43-730b-44cb-95e2-807dc2c941a7)
