### ISSUE TITLE
Unable to view weather page in webfrontend endpoint when running AspireWithDapr solution with error 'CreateFile .dapr\components: The system cannot find the path specified

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire-samples#65]
**REGRESSION INFO**: Worked fine with Aspire 8.0.0-preview.1.23557.2

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 Preview 2
3. Install Aspire Preview 2 latest build 8.0.0-preview.2.23610.1
4. Apply NuGet Feeds

**REPRO STEPS**
1. Clone aspire-samples repo
2. Checkout preview.2 branch
3. Update NuGet.config to use the dotnet-tools feed
4. Update Directory.Packages.props to use aspire version 8.0.0-preview.2.23610.1
6. Open solution AspireWithDapr.sln
7. Build and Ctrl+F5

**ACTUAL**
Initially, I ran the solution without installing dapr CLI. I get errors as shown below.

![image](https://github.com/dotnet/aspire-samples/assets/8246794/24d2285e-36d9-4e44-9911-72ad872def9c)

![image](https://github.com/dotnet/aspire-samples/assets/8246794/8e88a832-5afb-4f43-9fd6-a3452ff91d92)

After I install dapr CLI from [here](https://docs.dapr.io/getting-started/install-dapr-cli/), I now see the following error

![image](https://github.com/dotnet/aspire-samples/assets/8246794/76303237-b7d3-4310-9806-fed41691888d)

**EXPECTED**
Able to successfully run the AspireWithDapr solution

**Comment by balachir** [comment]
@davidfowl @DamianEdwards can you take a look, please?

**Comment by davidfowl** [comment]
@philliphoff seems like a regression maybe?

**Comment by balachir** [comment]
I had forgotten to run `dapr init`. It works fine now. I've sent a PR to update the README for preview 2.
