### ISSUE TITLE
[WebToolsE2E][Aspire] Failed to start container with running the Metrics solution: "Ports are not available: exposing port TCP 127.0.0.1:9090"

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#68]
**REGRESSION INFO:** Worked fine with Aspire 8.0.0-preview.1.23557.2

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 Preview 2
3. Install Aspire Preview 2 latest build 8.0.0-preview.2.23617.2
4. Apply NuGet Feeds
5. Install Docker Desktop

**REPRO STEPS**

1. Clone aspire-samples repo
2. Checkout preview.2 branch
3. Open solution Metrics.sln
4. Build and Ctrl+F5

**ACTUAL**
fail: Aspire.Hosting.Dcp.dcpctrl.ContainerReconciler[0]
      could not start the container     {"Controller": "usvc-dev.developer.microsoft.com/container-reconciler", "ContainerName": {"name":"prometheus"}, "Reconciliation": 5, "error": "RunContainer command returned error code 125 Stdout: '81cb928dcab9786e061fd2d083a1a2d7ea5d9f76fb6aa160fe184028d8536b9b\n' Stderr: 'docker: Error response from daemon: Ports are not available: exposing port TCP 127.0.0.1:9090 -> 0.0.0.0:0: listen tcp 127.0.0.1:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.\n'"}
![image](https://github.com/dotnet/aspire-samples/assets/71361488/d9f29ef8-5dd6-403c-8bb8-db2caacb2a77)
![image](https://github.com/dotnet/aspire-samples/assets/71361488/8dcc962c-f0fb-43fa-9392-2bc69af947f9)

**EXPECTED**

![image](https://github.com/dotnet/aspire-samples/assets/71361488/d15eca43-77a5-4354-baef-03338268a2d8)

**Comment by balachir** [comment]
I can reproduce this when I first run the Metrics solution with main branch checked out, and then run the solution again with preview 2 branch checked out. It seems that the Docker containers don't get cleaned up. Even if I manually delete the Docker containers and run again with preview 2 branch checked out, it can still reproduce this issue.

![image](https://github.com/dotnet/aspire-samples/assets/8246794/407213b1-69cb-421c-8dc3-e36ea6265e32)

**Comment by davidfowl** [comment]
This is fixed right?

**Comment by davidfowl** [comment]
Fixed by https://github.com/dotnet/aspire/pull/1455
