### ISSUE TITLE
Deploying AspireWithNode to Azure using azd doesn't deploy the node frontend

### ISSUE THREAD

**Issue by mrlund** [dotnet/aspire-samples#69]
I tried to deploy the AspireWithNode sample to azure using azd, as the ease of deployment was a highlighted feature of Aspire. From what I can tell it deployed the container with the redis cache and the webapi with the weatherforecast service, but not the frontend node app that connects to those two. 

I was particularly interested in seeing how that project would deploy, since being able to deploy a node project makes sense for at lot of SPA applications that might be able to leverage frontend framework features like SSR if they ran from node directly, rather than deploying the static build files to azure static apps, or through a regular app service. 

Steps: 
1) Clone this repo
2) cd into \samples\AspireWithNode\AspireWithNode.AppHost
3) azd init
4) azd up 

Additional note: the webapi project was deployed in a container. It would be nice to be able to deploy that as an app service instead.

**Comment by davidfowl** [comment]
This doesn’t work as yet. It will in preview 2

**Comment by mrlund** [comment]
Can confirm this works with preview 2, but it seems like normal webapi and web projects still only deploy as container apps. Will we get an option to deploy as app services too?

**Comment by davidfowl** [comment]
No we only support container apps, no plans for app service in the short term
