### ISSUE TITLE
AspireWithDapr project Errors 

### ISSUE THREAD

**Issue by salarvand** [dotnet/aspire-samples#73]
**AspireWithDapr** sample dose not work properly and gets this error in **apiservice-dapr** and **webfrontend-dapr** resources  :

> Error: could not create Endpoint object	{"Controller": "usvc-dev.developer.microsoft.com/executable-reconciler", "error": "service-producer annotation is invalid: missing information about the port to expose the service"}

> invalid argument "{{- portForServing \"apiservice-dapr_grpc\" -}}" for "-G, --dapr-grpc-port" flag: strconv.ParseInt: parsing "{{- portForServing \"apiservice-dapr_grpc\" -}}": invalid syntax
> Error: invalid argument "{{- portForServing \"apiservice-dapr_grpc\" -}}" for "-G, --dapr-grpc-port" flag: strconv.ParseInt: parsing "{{- portForServing \"apiservice-dapr_grpc\" -}}": invalid syntax

> invalid argument "{{- portForServing \"webfrontend-dapr_grpc\" -}}" for "-G, --dapr-grpc-port" flag: strconv.ParseInt: parsing "{{- portForServing \"webfrontend-dapr_grpc\" -}}": invalid syntax
> Error: invalid argument "{{- portForServing \"webfrontend-dapr_grpc\" -}}" for "-G, --dapr-grpc-port" flag: strconv.ParseInt: parsing "{{- portForServing \"webfrontend-dapr_grpc\" -}}": invalid syntax

Note : Dapr projects work properly standalone in my machine also other Aspire projects.

![image](https://github.com/dotnet/aspire-samples/assets/8214930/df3b49aa-53b6-4250-9578-33ec18cc454d)

![image](https://github.com/dotnet/aspire-samples/assets/8214930/7a9bb0f8-08a5-4c27-8623-bb2d645aa548)

![image](https://github.com/dotnet/aspire-samples/assets/8214930/5650c701-4269-44ee-aaaf-b3e0738801d8)

**Comment by davidfowl** [comment]
Try updating to preview2 of the workload:

```
dotnet workload update
dotnet workload install aspire
```

**Comment by salarvand** [comment]
Thanks, I update to preview 2 then everything is solved.
