### ISSUE TITLE
[WebToolsE2E][Aspire] After updating to Aspire 8.0 Preview 3, opening eShopLite.sln fails with: "Package downgrade detected: Microsoft.Extensions.Options from 8.0.1 to centrally defined 8.0.0"

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire-samples#90]
**REGRESSION INFO**: Worked fine with Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1[34511.213.main]
3. Install Aspire Preview 3 latest build 8.0.0-preview.3.24064.1
4. Apply NuGet Feeds
5. Install Docker Desktop

**REPRO STEPS**

1. Clone aspire-samples repo from main branch
2. Update NuGet.config to use the dotnet8 feed
 ![image](https://github.com/dotnet/aspire-samples/assets/71361488/393896f8-7a93-4f46-a135-46ba78643498)
3. Update Directory.Packages.props to use aspire version 8.0.0-preview.3.24064.1
4. Update global.json to use sdk version 8.0.200-preview.24060.48
6. Open solution eShopLite.sln

**NOTE**

- This issue also reproduces on Metrics / AspireWithNode solutions.

**ACTUAL**

NU1109	Detected package downgrade: Microsoft.Extensions.Options from 8.0.1 to centrally defined 8.0.0. Update the centrally managed package version to a higher version. 
 eShopLite.ServiceDefaults -> Microsoft.Extensions.ServiceDiscovery.Abstractions 8.0.0-preview.3.24064.1 -> Microsoft.Extensions.Options (>= 8.0.1) 
 eShopLite.ServiceDefaults -> Microsoft.Extensions.Options (>= 8.0.0)
![image](https://github.com/dotnet/aspire-samples/assets/71361488/c6747475-dc44-4d4b-9217-1d5a3b5dece4)

**EXPECTED**

Opening solution without any errors.

**OTHER INFO**
![image](https://github.com/dotnet/aspire-samples/assets/71361488/937643a3-00df-4199-9587-4156ed7dcbc2)

**Comment by joperezr** [comment]
I don't think this is a bug in aspire. Updating a project to a new version of Aspire is more than just updating Aspire.Hosting package versions. I do agree that the samples should be changed to target the latest shipped servicing (meaning reference 8.0.1) which would get rid of this warning.

In general, I'm expecting that going forward each time that we update the version of Aspire that the samples repo depends on we should ensure that we are also updating the platform so that it at least matches the version that Aspire references, if not newer.

**Comment by balachir** [comment]
@joperezr I investigated this some more today. I'm unable to get rid of this warning even when I update the runtime versions to 8.0.1 in Directory.Packages.props file of this repo.

From solution explorer, it seems to indicate that Aspire.Hosting 8.0.0-preview.3.24071.6 depends on Microsoft.Extensions.Hosting 8.0.0 depends on Microsoft.Extensions.Options 8.0.0. But other dependencies such as Aspire.StackExchange.Redis 8.0.0-preview.3.24071.6 depend on the 8.0.1 versions. Therefore, we see the downgrade warnings. 

**Question**: Does the Aspire.Hosting package need to be updated to depend on the 8.0.1 versions?

![image](https://github.com/dotnet/aspire-samples/assets/8246794/0c7f7600-4fde-42b4-b902-5c029ba3269f)


![image](https://github.com/dotnet/aspire-samples/assets/8246794/4e35f6c2-3ca4-4c96-b433-4b9bdc3082fb)

**Comment by DamianEdwards** [comment]
@balachir that error is saying that you still have `Microsoft.Extensions.Options` set to 8.0.0 in Central Package Management.

**Comment by balachir** [comment]
@DamianEdwards I'm unable to figure this out. With clean install of latest build of VS 17.10 P1, we get SDK 8.0.200-preview with 8.0.0 runtime. But VS 17.10 P1 will actually ship with SDK 8.0.200 with 8.0.2 runtime. So, I installed a build of SDK 8.0.200 with 8.0.2 runtime on my machine, pinned SDK version to 8.0.200 in global.json and updated all the versions in my Directory.Packages.props to 8.0.2. 

![image](https://github.com/dotnet/aspire-samples/assets/8246794/66c5177c-62b5-485e-ac12-0aa09c2dff34)

But I still get that same downgrade error
![image](https://github.com/dotnet/aspire-samples/assets/8246794/cb156adf-5600-43f6-8a88-50a45f17bef2)

**Comment by DamianEdwards** [comment]
What feeds are you using? Are there any other NuGet messages (info, warning)?

**Comment by DamianEdwards** [comment]
Note that the `Microsoft.Extensions.*` packages do not version together, e.g. right now there is no version of `Microsoft.Extensions.Hosting` higher than `8.0.0` on nuget.org, despite there being a `Microsoft.Extensions.Options` with version `8.0.1`. It's likely you'll have to manually configure versions for each `Microsoft.Extensions.*` package and get rid of the `RuntimeVersion` property.

**Comment by balachir** [comment]
@DamianEdwards @davidfowl I tried explicitly setting the version of `Microsoft.Extensions.Options` to 8.0.2 but I still can't get eshopLite to build. Other samples in the aspire-samples repo also have this same problem.

This is blocking all our validation using the samples from aspire-samples repo. Can you try it out and help unblock us? I've added the preview 3 milestone label to this issue for better visibility.

**Comment by balachir** [comment]
After some more trying, I got the solutions in aspire-samples repo to build successfully now. Following are the changes that I needed to make for Aspire 8.0 P3.

- Update global.json to point to .NET SDK 8.0.200 
![image](https://github.com/dotnet/aspire-samples/assets/8246794/72f5aa73-f53a-460b-b16e-797ab7c91d38)


- Update some versions in Directory.Packages.props
![image](https://github.com/dotnet/aspire-samples/assets/8246794/7cb67917-1cef-4a32-a009-8a11070c14cf)

![image](https://github.com/dotnet/aspire-samples/assets/8246794/db5be11e-41c9-4cbf-9c41-ca9e5f243b68)

**Comment by v-cazhang** [comment]
Tried to make following changes with latest Aspire 8.0.0-preview.3.24105.21, now can build solutions successfully.

- Update global.json 
![image](https://github.com/dotnet/aspire-samples/assets/82028229/7a4a2127-f86f-475e-a024-d59da32cf903)

- Update nuget.config to use the dotnet8rtm feed and dotnet-tool feed.

- Update Directory.Packages.props
![image](https://github.com/dotnet/aspire-samples/assets/82028229/b733c7a5-e7fc-4da4-8afb-10df49fe0e31)
![image](https://github.com/dotnet/aspire-samples/assets/82028229/19ca2d08-19b4-4f7a-9bdb-711988a70c0e)

**Comment by balachir** [comment]
Fixed with #108. Closing this issue.
