### ISSUE TITLE
[AzureTools][Aspire] The scroll bar of the page is not responding when scrolling the mouse wheel down or up

### ISSUE THREAD

**Issue by v-mengwe** [dotnet/aspire-samples#95]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version:** VS 17.10 Preview 1 from [34516.161.main]
**Aspire Version:** 8.0.0-preview.3.24066.3  
Apply NuGet Feeds

**REPRO STEPS:**
1. Create a new 8.0 project with "Enlist in .NET Aspire orchestration" checked.
2. F5 
3. In the dashboard, click "Metrics" -> Select a resource -> Drag the scroll bar of the page to the bottom. 
4. Click the "Filters" icon in the Filters -> Expand a filter window and the page scroll bar is no longer at the bottom. 
![image](https://github.com/dotnet/aspire-samples/assets/62053665/73b48f00-79c7-4c70-86fb-b9dc5bd95088)
5. The mouse focuses on the page -> Scroll mouse wheel down or up. 
6. Check whether the scroll bar of the page is responding.

**Expect:**
The scroll bar of the page is responding.

**Actual:** 
The scroll bar of the page is not responding.
https://github.com/dotnet/aspire-samples/assets/62053665/6f283670-44fa-4ccb-bf5f-dabfa8d3ba3f

**More Info:**
The mouse focuses on the opened filter window -> Scroll mouse wheel down -> The scroll bar of the page is responding.

**Comment by drewnoakes** [comment]
@adamint @JamesNK for awareness. I suspect we should move this to dotnet/aspire, rather than leaving it in the samples repo.

**Comment by v-mengwe** [comment]
Sorry for the wrong path, thanks for the reminder, I've moved it to dotnet/aspire [https://github.com/dotnet/aspire/issues/1707](url)
