### ISSUE TITLE
Issue running Aspire and Dapr Sample.

### ISSUE THREAD

**Issue by jgrusewski** [dotnet/aspire-samples#99]
Problem: 
When starting the AspirWithDapr Samples, or try my own code, the dapr sidecar fails to start.

Impact:
Dapr with Aspire services cannot communicate with each other.

Details: 

Dapr Version: dapr -v
CLI version: 1.12.0
Runtime version: 1.12.4

Visual Studio:
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.9.0 Preview 3.0

NuGet Packages: 
Aspire.Hosting.Dapr: 8.0.0-preview.2.23619.3
Aspire.Hosting: 8.0.0-preview.2.23619.3

Code Snippet App Host: 

var webOptions = new DaprSidecarOptions
{
    AppId = "api",
};

builder.AddProject<Web_App>("web.app")
   .WithDaprSidecar(webOptions);

Errors in logging:

	Aspire App Host Console Log:
		fail: Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
		      could not create Endpoint object  {"Controller": "usvc-dev.developer.microsoft.com/executable-reconciler", "error": "service-producer annotation is invalid: missing information about the port to expose the service"}

	Aspire Web Console Log: 
		web.app-dapr:
			invalid argument "{{- portForServing \"web.app-dapr_grpc\" -}}" for "-G, --dapr-grpc-port" flag: strconv.ParseInt: parsing "{{- portForServing \"web.app-dapr_grpc\" -}}": invalid syntax
Error: invalid argument "{{- portForServing \"web.app-dapr_grpc\" -}}" for "-G, --dapr-grpc-port" flag: strconv.ParseInt: parsing "{{- portForServing \"web.app-dapr_grpc\" -}}": invalid syntax

I probably doing something wrong, any ideas?

**Comment by davidfowl** [comment]
You need to update the workload to preview2 of aspire.

```
dotnet workload update
dotnet workload install aspire
```
